### ISSUE TITLE
Dockerfile issue

### ISSUE THREAD

**Issue by eranchetz** [doitintl/spot-asg#1]
When running `docker build .`
https://github.com/doitintl/spot-asg/blob/master/Dockerfile#L23 spits out an error
`Error response from daemon: Dockerfile parse error line 23: Unknown flag: mount`

**Comment by alexei-led** [comment]
Use

```
DOCKER_BUILDKIT=1 docker build ...
```

**Comment by eranchetz** [comment]
works like, charm, do you think we need to add this to the docs?
